version: "3.8"

services:
  app:
    build:
      context: .
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    ports:
      - "8000:9000"
    volumes:
      - .:/var/www
    networks:
      - laravel-network

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: userpassword
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - laravel-network
    ports:
      - "3306:3306"

volumes:
  db-data:

networks:
  laravel-network:
    driver: bridge
